[package]
name = "ruplacer"
version = "0.1.0"
authors = ["Dimitri Merejkowsky <d.merej@gmail.com>"]
description = "Find and replace text in files"
license = "BSD-3-Clause"


keywords = ["replacer", "find", "grep", "command", "line"]
categories = ["command-line-utilities"]

repository = "https://github.com/TankerApp/ruplacer"

[dependencies]
difference = "2.0"
ignore = "0.4"
structopt = "0.2"
colored = "1.6"


[dev-dependencies]
tempdir = "0.3"
