[package]
name = "ruplacer"
version = "0.1.0"
authors = ["Dimitri Merejkowsky <d.merej@gmail.com>"]
description = "Find and replace text in files"
license = "BSD-3-Clause"


keywords = ["replacer", "find", "grep", "command", "line"]
categories = ["command-line-utilities"]

repository = "https://github.com/TankerApp/ruplacer"

[dependencies]


[dev-dependencies]
tempdir = "0.3"
